#!/usr/bin/env sh

# This script is used when Docker Hub is automatically building the images

# Build such that the image tag is the container base
case $DOCKER_TAG in
  latest | "")
    docker build -t $IMAGE_NAME .
    ;;

  *)
    echo "Building using the base image: $DOCKER_TAG"
    docker build --build-arg=BASE=$DOCKER_TAG -t $IMAGE_NAME .
    ;;
esac