name: Publish Docker image

on: [push]

jobs:
  push_to_registries:
    name: Push Docker image to GitHub registry
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag: [latest, node, python, [python, 3.7]]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: ${{ github.repository }}/cde
          tags: ${{ join(matrix.tag, '-') }}
          build_args: BASE=${{ join(matrix.tag, ':') }}
