name: Publish Docker image

on: [push]

jobs:
  push_to_registries:
    name: Push image to GitHub Container Registry
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag: [node, python, [python, 3.7]]

    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.tag }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: BASE=${{ join(matrix.tag, ':') }}
          tags: ghcr.io/${{ github.repository }}:${{ join(matrix.tag, '-') }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
